const { Product } = require('../models');

const productData = [
  {
    product_name: '18V Brushless Hammer Driver Drill Kit',
    product_make: 'Makita',
    product_model: 'DHP485SF',
    description: 'The Makita 18V Mobile Brushless Hammer Driver drill features a high performance brushless DC motor.',
    daily_rate: 45.00,
    user_manual: 'https://media.makita.co.nz/_media/user-manuals/D/DHP485-UG.pdf',
    owner_id: 1,
    category_id: 1,
},
{
    product_name: '100mm (4") 850W Angle Grinder',
    product_make: 'Ozito',
    product_model: 'AGS-4050',
    description: 'The Ozito 100mm (4”) Angle Grinder is a handy addition to your tool shed. It can be used for a variety of different metal working applications.',
    daily_rate: 32.00,
    user_manual: 'https://delivery.bunningscontenthub.bunnings.com.au/api/public/content/f325044876bd46a194fdfce5c5e2f98f?v=0cce0928',
    owner_id: 1,
    category_id: 1,
},
{
    product_name: 'Masport Cleveland 18" Hand Lawn Mower',
    product_make: 'Masport',
    product_model: '552803',
    description: `Perfect for those small jobs, the Masport 460 hand mower offers a 460mm cutting width and a 13 to 56 mm cutting height.`,
    daily_rate: 30.00,
    user_manual: 'https://masport.com.au/outdoor-garden-products/outdoor-power-equipment/hand-and-electric-mowers/cleveland-18-',
    owner_id: 2,
    category_id: 2,
},
{
    product_name: 'ERGO™ 20 mm Medium Left Handed Bypass Secateurs with Elastomer Coated Rotating Handle',
    product_make: 'Bahco',
    product_model: 'PXR-M2-L',
    description: 'Maximum comfort with minimum effort due to the ergonomic design.',
    daily_rate: 15.00,
    user_manual: 'https://media.makita.co.nz/_media/user-manuals/D/DHP485-UG.pdf',
    owner_id: 2,
    category_id: 2,
},
{
    product_name: 'Britex Carpet Care Machine',
    product_make: 'Britex',
    product_model: 'BR-11',
    description: 'Using the power of hot water extraction the Britex cleaning machine reaches deep into your carpet fibres and fabric furnishings.',
    daily_rate: 80.00,
    user_manual: 'https://britex.com/wp-content/uploads/2022/10/221012-BR0007A-Britex-8pp-DL-Brochure-DIGITAL.pdf',
    owner_id: 3,
    category_id: 3,
},
{
    product_name: 'Gerni 1885PSI High Pressure Washer',
    product_make: 'Gerni',
    product_model: 'GPW-5000',
    description: `This powerful 1885psi high-pressure washer offers great performance and durability with a long-lasting aluminium pump.`,
    daily_rate: 45.00,
    user_manual: 'https://media.makita.co.nz/_media/user-manuals/D/DHP485-UG.pdf',
    owner_id: 3,
    category_id: 3,
},
{
    product_name: '6 X 4 Heavy Duty Trailer',
    product_make: 'Blue Star Trailers',
    product_model: 'BST-6X4HD',
    description: 'This is 100% Australian made single-axle trailer using locally sourced steel.',
    daily_rate: 100.00,
    user_manual: 'https://www.bluestartrailers.com.au/6-x-4-heavy-duty-trailer/',
    owner_id: 4,
    category_id: 4,
},
{
    product_name: '9 x 5 Tipper Trailer',
    product_make: 'Blue Star Trailers',
    product_model: 'BST-9X5T',
    description: '9 x 5 Tipper Trailer uses hydraulic brakes, LED lights and 4 stage RAM.',
    daily_rate: 110.00,
    user_manual: 'https://www.bluestartrailers.com.au/9-x-5-tipper-trailer/',
    owner_id: 4,
    category_id: 4,
},
{
    product_name: 'Daytek Tradesman Poly 120L',
    product_make: 'Daytek',
    product_model: 'A02840681',
    description: 'The Tradesman with Poly Bowl is the ideal barrow for those carrying large loads.',
    daily_rate: 15.00,
    user_manual: 'https://www.bunnings.com.au/daytek-120l-poly-tradesman-wheelbarrow_p0043314',
    owner_id: 5,
    category_id: 5,
},
{
    product_name: 'DeWALT 2,200W Inverter Generator',
    product_make: 'DeWalt',
    product_model: 'DXIG2200',
    description: 'DeWALT powered generators are GUARANTEED TOUGH®.',
    daily_rate: 120.00,
    user_manual: 'https://www.bunnings.com.au/dewalt-2200w-inverter-generator_p0116145',
    owner_id: 5,
    category_id: 5,
},
];

const seedProducts = () => Product.bulkCreate(productData);

module.exports = seedProducts;
